version: '3'

services:
  app:
    build: .
    entrypoint:
      - .docker/entrypoint.sh
    container_name: app-vote
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - .:/home/node/app
    depends_on:
      - db_staging
    env_file:
      - .env
    networks:
      - mongo-compose-network
  db_staging:
    image: mongo
    container_name: db-staging
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testDb23root
    ports:
      - "27017:27017"
    volumes:
      - .docker/dbdata:/data/db
    networks:
      - mongo-compose-network
    logging:
      driver: "none"
  db_test:
    image: mongo
    container_name: db-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testDb23root
    ports:
      - "27018:27017"
    volumes:
      - .docker/dbdatatest:/data/db
    networks:
      - mongo-compose-network
    logging:
      driver: "none"
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://root:testDb23root@mongo:27017/
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_BASICAUTH_USERNAME: user
  #     ME_CONFIG_BASICAUTH_PASSWORD: testDb23!
  #   links:
  #     - mongo
  #   networks:
  #     - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge
